# yaml-language-server: $schema=https://raw.githubusercontent.com/awslabs/goformation/master/schema/cloudformation.schema.json

AWSTemplateFormatVersion: '2010-09-09'
Description: 'NT548 LAB 01 - AWS Infrastructure with CloudFormation
  Complete infrastructure including VPC, Subnets, IGW, NAT, Route Tables, Security Groups, and EC2 Instances'

# ============================================================================
# METADATA
# ============================================================================
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - VpcCIDR
          - PublicSubnetCIDR
          - PrivateSubnetCIDR
      - Label:
          default: "EC2 Configuration"
        Parameters:
          - KeyName
          - InstanceType
          - MyIP
      - Label:
          default: "Project Tags"
        Parameters:
          - ProjectName
          - Environment
    ParameterLabels:
      VpcCIDR:
        default: "VPC CIDR Block"
      PublicSubnetCIDR:
        default: "Public Subnet CIDR"
      PrivateSubnetCIDR:
        default: "Private Subnet CIDR"
      KeyName:
        default: "EC2 Key Pair Name"
      MyIP:
        default: "Your IP Address (for SSH)"

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  ProjectName:
    Type: String
    Default: nt548-lab01
    Description: Project name for resource tagging

  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod

  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for VPC (65,536 IPs)
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'

  PublicSubnetCIDR:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for Public Subnet (256 IPs)
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'

  PrivateSubnetCIDR:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for Private Subnet (256 IPs)
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: nt548-lab01-key
    Description: EC2 Key Pair for SSH access

  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 Instance Type (Free Tier eligible)
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small

  MyIP:
    Type: String
    Default: 42.113.225.23/32
    Description: Your IP address for SSH access (IMPORTANT - Update this!)
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id
    Description: Latest Ubuntu 24.04 LTS AMI ID (auto-fetched from SSM)

# ============================================================================
# RESOURCES
# ============================================================================
Resources:

  # ==========================================================================
  # 1. VPC
  # ==========================================================================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==========================================================================
  # 2. INTERNET GATEWAY
  # ==========================================================================
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'
        - Key: Project
          Value: !Ref ProjectName

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ==========================================================================
  # 3. SUBNETS
  # ==========================================================================
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCIDR
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-subnet'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Type
          Value: Public

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCIDR
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-subnet'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Type
          Value: Private

  # ==========================================================================
  # 4. NAT GATEWAY (for Private Subnet)
  # ==========================================================================
  NATGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-nat-eip'
        - Key: Project
          Value: !Ref ProjectName

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-nat-gateway'
        - Key: Project
          Value: !Ref ProjectName

  # ==========================================================================
  # 5. ROUTE TABLES
  # ==========================================================================
  
  # Public Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-rt'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Type
          Value: Public

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Private Route Table
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-rt'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Type
          Value: Private

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # ==========================================================================
  # 6. SECURITY GROUPS
  # ==========================================================================
  
  # Public Security Group (for Public EC2)
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-public-sg'
      GroupDescription: Security group for Public EC2 - SSH from specific IP only
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # SSH from specific IP only (2-point requirement!)
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
          Description: SSH from my IP only
        # HTTP from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP from anywhere
        # HTTPS from anywhere
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS from anywhere
      SecurityGroupEgress:
        # Allow all outbound traffic
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-sg'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Type
          Value: Public

  # Private Security Group (for Private EC2)
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-private-sg'
      GroupDescription: Security group for Private EC2 - Access from Public SG only
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # SSH from Public Security Group
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroup
          Description: SSH from Public EC2
        # All TCP from Public Security Group
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref PublicSecurityGroup
          Description: All TCP from Public EC2
        # ICMP (ping) from Public Security Group
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          SourceSecurityGroupId: !Ref PublicSecurityGroup
          Description: ICMP from Public EC2
      SecurityGroupEgress:
        # Allow all outbound traffic (through NAT)
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-sg'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Type
          Value: Private

  # ==========================================================================
  # 7. EC2 INSTANCES
  # ==========================================================================
  
  # Public EC2 Instance
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: AttachGateway
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
            Encrypted: true
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          apt-get update -y
          apt-get upgrade -y
          
          # Install Docker
          apt-get install -y docker.io
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ubuntu
          
          # Install AWS CLI
          apt-get install -y awscli
          
          # Install useful tools
          apt-get install -y htop vim git wget curl net-tools
          
          # Create welcome banner
          cat > /etc/update-motd.d/99-custom << 'EOF'
          #!/bin/sh
          echo "======================================"
          echo "  Welcome to Public EC2 Instance"
          echo "  NT548 Lab 01 - CloudFormation Demo"
          echo "  Project: ${ProjectName}"
          echo "  Environment: ${Environment}"
          echo "======================================"
          EOF
          chmod +x /etc/update-motd.d/99-custom
          
          # Remove default Ubuntu MOTD files
          chmod -x /etc/update-motd.d/10-help-text
          chmod -x /etc/update-motd.d/50-motd-news
          
          # System info
          echo "Public EC2 Instance initialized at $(date)" > /var/log/userdata.log
          echo "Instance ID: $(ec2-metadata --instance-id | cut -d ' ' -f 2)" >> /var/log/userdata.log
          echo "Public IP: $(ec2-metadata --public-ipv4 | cut -d ' ' -f 2)" >> /var/log/userdata.log
          echo "Private IP: $(ec2-metadata --local-ipv4 | cut -d ' ' -f 2)" >> /var/log/userdata.log
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-ec2'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Public

  # Private EC2 Instance
  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
            Encrypted: true
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          apt-get update -y
          apt-get upgrade -y
          
          # Install Docker
          apt-get install -y docker.io
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ubuntu
          
          # Install AWS CLI
          apt-get install -y awscli
          
          # Install useful tools
          apt-get install -y htop vim git wget curl net-tools
          
          # Create welcome banner
          cat > /etc/update-motd.d/99-custom << 'EOF'
          #!/bin/sh
          echo "======================================"
          echo "  Welcome to Private EC2 Instance"
          echo "  NT548 Lab 01 - CloudFormation Demo"
          echo "  Project: ${ProjectName}"
          echo "  Environment: ${Environment}"
          echo "  Note: Internet access via NAT Gateway"
          echo "======================================"
          EOF
          chmod +x /etc/update-motd.d/99-custom
          
          # Remove default Ubuntu MOTD files
          chmod -x /etc/update-motd.d/10-help-text
          chmod -x /etc/update-motd.d/50-motd-news
          
          # System info
          echo "Private EC2 Instance initialized at $(date)" > /var/log/userdata.log
          echo "Instance ID: $(ec2-metadata --instance-id | cut -d ' ' -f 2)" >> /var/log/userdata.log
          echo "Private IP: $(ec2-metadata --local-ipv4 | cut -d ' ' -f 2)" >> /var/log/userdata.log
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-ec2'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPC-ID'

  VPCCidr:
    Description: VPC CIDR Block
    Value: !Ref VpcCIDR
    Export:
      Name: !Sub '${AWS::StackName}-VPC-CIDR'

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet-ID'

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnet-ID'

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway
    Export:
      Name: !Sub '${AWS::StackName}-IGW-ID'

  NATGatewayId:
    Description: NAT Gateway ID
    Value: !Ref NATGateway
    Export:
      Name: !Sub '${AWS::StackName}-NAT-ID'

  NATGatewayEIP:
    Description: NAT Gateway Elastic IP
    Value: !Ref NATGatewayEIP
    Export:
      Name: !Sub '${AWS::StackName}-NAT-EIP'

  PublicRouteTableId:
    Description: Public Route Table ID
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub '${AWS::StackName}-PublicRT-ID'

  PrivateRouteTableId:
    Description: Private Route Table ID
    Value: !Ref PrivateRouteTable
    Export:
      Name: !Sub '${AWS::StackName}-PrivateRT-ID'

  PublicSecurityGroupId:
    Description: Public Security Group ID
    Value: !Ref PublicSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-PublicSG-ID'

  PrivateSecurityGroupId:
    Description: Private Security Group ID
    Value: !Ref PrivateSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSG-ID'

  PublicEC2InstanceId:
    Description: Public EC2 Instance ID
    Value: !Ref PublicEC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-PublicEC2-ID'

  PublicEC2PublicIP:
    Description: Public EC2 Instance Public IP
    Value: !GetAtt PublicEC2Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicEC2-PublicIP'

  PublicEC2PrivateIP:
    Description: Public EC2 Instance Private IP
    Value: !GetAtt PublicEC2Instance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicEC2-PrivateIP'

  PrivateEC2InstanceId:
    Description: Private EC2 Instance ID
    Value: !Ref PrivateEC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-PrivateEC2-ID'

  PrivateEC2PrivateIP:
    Description: Private EC2 Instance Private IP (NO PUBLIC IP)
    Value: !GetAtt PrivateEC2Instance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-PrivateEC2-PrivateIP'

  SSHCommand:
    Description: SSH Command to connect to Public EC2
    Value: !Sub 'ssh -i ${KeyName}.pem ubuntu@${PublicEC2Instance.PublicIp}'

  Architecture:
    Description: Infrastructure Architecture Summary
    Value: !Sub |
      VPC: ${VPC} (${VpcCIDR})
      Public Subnet: ${PublicSubnet} (${PublicSubnetCIDR})
      Private Subnet: ${PrivateSubnet} (${PrivateSubnetCIDR})
      NAT Gateway: ${NATGateway} (EIP: ${NATGatewayEIP})
      Public EC2: ${PublicEC2Instance.PublicIp} (SSH allowed from ${MyIP})
      Private EC2: ${PrivateEC2Instance.PrivateIp} (NO Public IP - Access via NAT)
